/**
 * study-api — client-side data layer for the Side-by-Side Study Pane.
 *
 * Backed by cacheable static assets (see `lib/study-data.ts`, generated by
 * `scripts/build-study-assets.ts`) with in-memory caching, so chapter
 * navigation feels instant after the first load.
 */

import {
  getChapterTexts,
  getInterlinearChapter,
  getPericopes,
  getStrongsEntry,
} from './study-data';
import { verseCount as canonVerseCount } from './study-utils';

export type StudyToken = {
  w: string;
  strongs: string;
  transliteration?: string;
  gloss?: string;
  morph?: string;
};

export type StudyVerse = {
  verse: number;
  primary: string | null;
  secondary: string | null;
  interlinear: StudyToken[];
};

export type StudyPericope = {
  id: string;
  title: string;
  book: string;
  chapter: number;
  startVerse: number;
  endVerse: number;
  reference: string;
  category?: string;
};

export type StudyChapter = {
  book: string;
  chapter: number;
  primary: string;
  secondary: string;
  verseCount: number;
  verses: StudyVerse[];
  pericopes: StudyPericope[];
};

export type StrongsDetail = {
  id: string;
  lexeme?: string;
  transliteration?: string;
  pronunciation?: string;
  short_definition?: string;
  definition?: string;
};

const chapterCache = new Map<string, Promise<StudyChapter | null>>();
const strongsCache = new Map<string, Promise<StrongsDetail | null>>();

function chapterKey(book: string, chapter: number, primary: string, secondary: string): string {
  return `${book.toUpperCase()}:${chapter}:${primary.toUpperCase()}:${secondary.toUpperCase()}`;
}

export function clearStudyCache(): void {
  chapterCache.clear();
  strongsCache.clear();
}

async function assembleChapter(
  book: string,
  chapter: number,
  primary: string,
  secondary: string
): Promise<StudyChapter | null> {
  const upperBook = book.toUpperCase();
  const [primaryData, secondaryData, interlinear] = await Promise.all([
    getChapterTexts(primary, upperBook, chapter),
    secondary.toUpperCase() === primary.toUpperCase()
      ? Promise.resolve(null)
      : getChapterTexts(secondary, upperBook, chapter),
    getInterlinearChapter(upperBook, chapter),
  ]);

  const dataCount = Math.max(primaryData?.count ?? 0, secondaryData?.count ?? 0);
  if (dataCount === 0) return null;
  // Prefer the canonical verse count so a missing trailing verse in one
  // translation cannot inflate or shrink the chapter grid.
  const canonical = canonVerseCount(upperBook, chapter);
  const total = canonical > 0 ? canonical : dataCount;

  const verses: StudyVerse[] = Array.from({ length: total }, (_, i) => {
    const verse = i + 1;
    const key = String(verse);
    return {
      verse,
      primary: primaryData?.texts[key] ?? null,
      secondary:
        secondary.toUpperCase() === primary.toUpperCase()
          ? (primaryData?.texts[key] ?? null)
          : (secondaryData?.texts[key] ?? null),
      interlinear: interlinear[key] ?? [],
    };
  });

  return {
    book: upperBook,
    chapter,
    primary: primary.toUpperCase(),
    secondary: secondary.toUpperCase(),
    verseCount: total,
    verses,
    pericopes: getPericopes(upperBook, chapter),
  };
}

/** Fetches a full chapter (primary + secondary + interlinear + pericopes). */
export function fetchStudyChapter(
  book: string,
  chapter: number,
  primary = 'BSB',
  secondary = 'KJV'
): Promise<StudyChapter | null> {
  const key = chapterKey(book, chapter, primary, secondary);
  const cached = chapterCache.get(key);
  if (cached) return cached;
  const loader = assembleChapter(book, chapter, primary, secondary).catch(() => null);
  chapterCache.set(key, loader);
  // Evict failed loads so a retry can happen.
  loader.then((result) => {
    if (!result) chapterCache.delete(key);
  });
  return loader;
}

/** Fetches the Strong's dictionary entry for a token tooltip. */
export function fetchStrongsDetail(id: string): Promise<StrongsDetail | null> {
  const normalized = id.trim().toUpperCase();
  if (!normalized) return Promise.resolve(null);
  const cached = strongsCache.get(normalized);
  if (cached) return cached;
  const loader = getStrongsEntry(normalized)
    .then((entry) => (entry ? { id: normalized, ...entry } : null))
    .catch(() => null);
  strongsCache.set(normalized, loader);
  loader.then((result) => {
    if (!result) strongsCache.delete(normalized);
  });
  return loader;
}

/** Prefetches the neighbouring chapters for zero-latency prev/next. */
export function prefetchAdjacentChapters(
  book: string,
  chapter: number,
  primary: string,
  secondary: string,
  maxChapter: number
): void {
  if (typeof window === 'undefined') return;
  const schedule = window.requestIdleCallback ?? ((cb: () => void) => window.setTimeout(cb, 800));
  schedule(() => {
    if (chapter > 1) void fetchStudyChapter(book, chapter - 1, primary, secondary);
    if (chapter < maxChapter) void fetchStudyChapter(book, chapter + 1, primary, secondary);
  });
}
