/**
 * study-data — static-asset loaders for the Side-by-Side Study Pane.
 *
 * Data is generated by `scripts/build-study-assets.ts` into `public/data/`
 * (served by Vite in dev, ASSETS in production), so chapter navigation never
 * touches worker compute or the network beyond cacheable static files:
 *
 *   /data/translations-index.json
 *   /data/translations/<book-file>.json   -> { "<chapter>": { "<verse>": text } }
 *   /data/interlinear/<BOOK>-<chapter>.json -> { verses: { "25": [{ w, s, m?, tr?, g? }] } }
 *   /data/strongs-dict.json               -> { "G4541": {...} } (lazy, one-time)
 *
 * The fetch implementation is injectable for unit tests.
 */

import rawPericopes from '@/data/pericopes.json';
import type { StudyPericope, StudyToken } from './study-api';

export type FetchLike = (
  url: string
) => Promise<{ ok: boolean; status: number; json: () => Promise<unknown> }>;

let fetchImpl: FetchLike = (url) =>
  fetch(url).then((res) => ({
    ok: res.ok,
    status: res.status,
    json: () => res.json() as Promise<unknown>,
  }));

/** Overrides the fetch implementation (unit tests). */
export function setStudyFetchImpl(impl: FetchLike | null): void {
  fetchImpl =
    impl ??
    ((url) =>
      fetch(url).then((res) => ({
        ok: res.ok,
        status: res.status,
        json: () => res.json() as Promise<unknown>,
      })));
}

type TranslationBook = Record<string, Record<string, string>>;
type CompactChapterFile = {
  verses?: Record<string, Array<{ w: string; s: string; m?: string; tr?: string; g?: string }>>;
};

const indexCache: { translations?: Record<string, Record<string, string>> } = {};
let indexInFlight: Promise<Record<string, Record<string, string>>> | null = null;
const bookCache = new Map<string, TranslationBook | null>();
const interlinearCache = new Map<string, Record<string, StudyToken[]>>();
let strongsCache: Record<string, {
  transliteration?: string;
  short_definition?: string;
  definition?: string;
  lexeme?: string;
  pronunciation?: string;
}> | null = null;
let strongsInFlight: Promise<unknown> | null = null;

export function clearStudyDataCache(): void {
  delete indexCache.translations;
  indexInFlight = null;
  bookCache.clear();
  interlinearCache.clear();
  strongsCache = null;
  strongsInFlight = null;
}

async function fetchJsonOrNull<T>(url: string): Promise<T | null> {
  try {
    const res = await fetchImpl(url);
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

function normalizeTranslation(input: string): string {
  return input.trim().toUpperCase();
}

async function getTranslationsIndex(): Promise<Record<string, Record<string, string>>> {
  if (indexCache.translations) return indexCache.translations;
  if (!indexInFlight) {
    indexInFlight = fetchJsonOrNull<Record<string, Record<string, string>>>(
      '/data/translations-index.json'
    )
      .then((index) => {
        indexCache.translations = index ?? {};
        return indexCache.translations;
      })
      .finally(() => {
        indexInFlight = null;
      });
  }
  return indexInFlight;
}

async function getTranslationBook(translation: string, book: string): Promise<TranslationBook | null> {
  const key = `${normalizeTranslation(translation)}:${book.toUpperCase()}`;
  if (bookCache.has(key)) return bookCache.get(key) ?? null;
  const index = await getTranslationsIndex();
  const file = index[normalizeTranslation(translation)]?.[book.toUpperCase()];
  if (!file || file.includes('..')) {
    bookCache.set(key, null);
    return null;
  }
  const data = await fetchJsonOrNull<TranslationBook>(
    `/data/translations/${encodeURIComponent(file)}`
  );
  bookCache.set(key, data);
  return data;
}

/** Chapter texts for one translation; null when unavailable. */
export async function getChapterTexts(
  translation: string,
  book: string,
  chapter: number
): Promise<{ texts: Record<string, string>; count: number } | null> {
  const data = await getTranslationBook(translation, book);
  const chapterData = data?.[String(chapter)];
  if (!chapterData || Object.keys(chapterData).length === 0) return null;
  const numbers = Object.keys(chapterData).map(Number).filter(Number.isFinite);
  return { texts: chapterData, count: numbers.length > 0 ? Math.max(...numbers) : 0 };
}

/** Interlinear tokens for a chapter, keyed by verse number. Empty when unavailable. */
export async function getInterlinearChapter(
  book: string,
  chapter: number
): Promise<Record<string, StudyToken[]>> {
  const key = `${book.toUpperCase()}-${chapter}`;
  const cached = interlinearCache.get(key);
  if (cached) return cached;
  const file = await fetchJsonOrNull<CompactChapterFile>(
    `/data/interlinear/${encodeURIComponent(key)}.json`
  );
  const result: Record<string, StudyToken[]> = {};
  for (const [verse, tokens] of Object.entries(file?.verses ?? {})) {
    if (!Array.isArray(tokens)) continue;
    const mapped: StudyToken[] = [];
    for (const token of tokens) {
      if (!token?.w || !token?.s) continue;
      const out: StudyToken = { w: token.w, strongs: token.s };
      if (token.tr) out.transliteration = token.tr;
      if (token.g) out.gloss = token.g;
      if (token.m) out.morph = token.m;
      mapped.push(out);
    }
    if (mapped.length > 0) result[verse] = mapped;
  }
  interlinearCache.set(key, result);
  return result;
}

/** Strong's dictionary entry; null when unknown. Dictionary loads once, lazily. */
export async function getStrongsEntry(id: string): Promise<{
  lexeme?: string;
  transliteration?: string;
  pronunciation?: string;
  short_definition?: string;
  definition?: string;
} | null> {
  const normalized = id.trim().toUpperCase();
  if (!/^[HG]\d{1,5}$/.test(normalized)) return null;
  if (!strongsCache) {
    if (!strongsInFlight) {
      strongsInFlight = (async () => {
        strongsCache =
          (await fetchJsonOrNull<Record<string, {
            transliteration?: string;
            short_definition?: string;
            definition?: string;
            lexeme?: string;
            pronunciation?: string;
          }>>('/data/strongs-dict.json')) ?? {};
      })().finally(() => {
        strongsInFlight = null;
      });
    }
    await strongsInFlight;
  }
  return strongsCache?.[normalized] ?? null;
}

/** Pericopes bundled with the client (16KB) — no fetch needed. */
export function getPericopes(book?: string, chapter?: number): StudyPericope[] {
  const items = (Array.isArray(rawPericopes) ? rawPericopes : []) as StudyPericope[];
  return items
    .filter((p) => {
      if (book && p.book !== book.toUpperCase()) return false;
      if (chapter !== undefined && p.chapter !== chapter) return false;
      return true;
    })
    .sort((a, b) => a.startVerse - b.startVerse);
}
